[workspace]
# Use the newer version of the cargo resolver
# https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
resolver = "2"
members = ["xtask/", "crates/*"]

# TODO: Possibly setup profiles for dev to speed up tests/etc

# TODO: Setup release profile (incremental mode?)
[profile.release]
debug = true